name: Build Geode Mod
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          sdk: nightly
          target: win64
      - uses: actions/upload-artifact@v4
        with:
          name: GDOverlayBridge
          path: ${{ steps.build.outputs.build-output }}
